# Generated by Django 6.0 on 2025-12-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thingsboard_id', models.UUIDField(help_text='Device ID from Thingsboard')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farm')),
            ],
        ),
    ]
