# Generated by Django 5.2.9 on 2026-02-14 03:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_asset_id_alter_device_id_alter_farm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('crop_classification', 'Crop Classification'), ('disease_detection', 'Disease Detection'), ('yield_prediction', 'Yield Prediction'), ('weed_detection', 'Weed Detection'), ('soil_moisture', 'Soil Moisture Estimation'), ('irrigation_classification', 'Irrigation Classification'), ('microclimate', 'Micro Climate Prediction'), ('ndvi_anomaly', 'NDVI Anomaly Detection')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model_path', models.CharField(help_text='Path on disk or in MinIO bucket', max_length=500)),
                ('architecture', models.CharField(blank=True, help_text='e.g., RandomForest, GBR, ResNet50', max_length=100)),
                ('framework', models.CharField(default='scikit-learn', max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('f1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('training_dataset', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('satellite', 'Satellite Image'), ('drone', 'Drone Image'), ('sensor', 'Sensor Data'), ('combined', 'Multi-Source Fusion')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('prediction', models.JSONField(help_text='Model output — probabilities, values, maps, etc.')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('result_image_path', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='core.fieldboundary')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='ai_engine.mlmodel')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('crop_classification', 'Crop Classification'), ('disease_detection', 'Disease Detection'), ('yield_prediction', 'Yield Prediction'), ('weed_detection', 'Weed Detection'), ('soil_moisture', 'Soil Moisture Estimation'), ('irrigation_classification', 'Irrigation Classification'), ('microclimate', 'Micro Climate Prediction'), ('ndvi_anomaly', 'NDVI Anomaly Detection')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Training hyperparameters and options')),
                ('result_metrics', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fieldboundary')),
                ('trained_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='ai_engine.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
