# Generated by Django 5.2.9 on 2025-12-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asset_id_alter_device_id_alter_farm_id_and_more'),
        ('iot', '0002_alter_sensorreading_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation in mm', null=True)),
                ('precipitation_probability', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in km/h', null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('solar_radiation', models.FloatField(blank=True, help_text='Solar radiation W/m²', null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('conditions', models.CharField(blank=True, help_text='e.g., Sunny, Cloudy, Rainy', max_length=100)),
                ('source', models.CharField(default='manual', help_text='e.g., NOAA, OpenWeather, manual', max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='core.farm')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
