# Generated by Django 5.2.9 on 2025-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='results',
            field=models.JSONField(default=dict, help_text='Flexible key-value store for sensor data (temperature, moisture, pH, etc.)'),
        ),
    ]
