# Generated by Django 6.0 on 2025-12-23 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('avg_ndvi', models.FloatField(help_text='Average NDVI value (0-1)')),
                ('irrigation_alert', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fieldboundary')),
            ],
        ),
    ]
