# Generated by Django 5.2.9 on 2025-12-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsresult_id'),
        ('core', '0004_alter_asset_id_alter_device_id_alter_farm_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsresult',
            name='avg_ndwi',
            field=models.FloatField(blank=True, help_text='Average NDWI value (-1 to 1)', null=True),
        ),
        migrations.CreateModel(
            name='CropClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detected_crop', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Classification confidence 0-1')),
                ('healthy_area_percent', models.FloatField(default=0)),
                ('stressed_area_percent', models.FloatField(default=0)),
                ('bare_soil_percent', models.FloatField(default=0)),
                ('water_area_percent', models.FloatField(default=0)),
                ('source_image', models.CharField(blank=True, help_text='Path to source imagery', max_length=500)),
                ('result_image', models.CharField(blank=True, help_text='Path to classified result', max_length=500)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_classifications', to='core.fieldboundary')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(help_text='When the crop was planted')),
                ('crop_type', models.CharField(max_length=100)),
                ('predicted_emergence_date', models.DateField(blank=True, null=True)),
                ('predicted_harvest_date', models.DateField(blank=True, null=True)),
                ('current_growth_stage', models.CharField(choices=[('germination', 'Germination'), ('emergence', 'Emergence'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting/Grain Fill'), ('maturity', 'Maturity'), ('harvest_ready', 'Harvest Ready')], default='unknown', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Prediction confidence 0-1')),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_predictions', to='core.fieldboundary')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('annual', 'Annual')], max_length=20)),
                ('total_emissions', models.FloatField(help_text='Total emissions in tonnes CO2e')),
                ('soil_carbon_sequestration', models.FloatField(default=0, help_text='Carbon stored in soil')),
                ('net_carbon', models.FloatField(help_text='Net carbon (negative = carbon sink)')),
                ('fertilizer_emissions', models.FloatField(default=0)),
                ('fuel_emissions', models.FloatField(default=0)),
                ('livestock_emissions', models.FloatField(default=0)),
                ('crop_residue_emissions', models.FloatField(default=0)),
                ('tillage_practice', models.CharField(blank=True, choices=[('conventional', 'Conventional'), ('reduced', 'Reduced'), ('no_till', 'No-Till')], max_length=50)),
                ('cover_crops', models.BooleanField(default=False)),
                ('crop_rotation', models.BooleanField(default=False)),
                ('sustainability_score', models.FloatField(default=0, help_text='0-100 sustainability rating')),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_estimates', to='core.farm')),
            ],
            options={
                'ordering': ['-year', 'season'],
                'unique_together': {('farm', 'year', 'season')},
            },
        ),
    ]
