# Generated by Django 5.2.9 on 2025-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticsresult_avg_ndwi_cropclassification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestprediction',
            name='days_to_harvest',
            field=models.IntegerField(blank=True, help_text='Days remaining until harvest', null=True),
        ),
        migrations.AlterField(
            model_name='harvestprediction',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
