"""
Django settings for farm_system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ye^xsc)w)9@-^oq$bp=#37fct*)%#j3wip6^_zdx^4(-5gmqzv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Additional apps
    'django.contrib.gis',  # This enables PostGIS (Maps support)
    'django.contrib.humanize',  # optional but good for dashboards

    'rest_framework',      # This helps us build APIs
    'django_filters',           # filter telemetry / images / assets via API
    'storages',                 # for MinIO S3-compatible storage
    'django_celery_results',    # async processing results (NDVI, drone analysis)
    'django_celery_beat',       # scheduled tasks for analytics or ingestion
    'leaflet',                  # map visualization in admin/dashboard
    
    'core',
    'iot',
    'imagery',
    'analytics',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farm_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farm_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'farmdb',
        'USER': 'farm_user',      # The user we just created
        'PASSWORD': 'farm_pass',  # The password we just set
        'HOST': 'localhost',
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# MinIO Configuration
MINIO_ENDPOINT = 'localhost:9000'
MINIO_ACCESS_KEY = 'minioadmin'
MINIO_SECRET_KEY = 'minioadmin'
MINIO_BUCKET_NAME = 'farm-data'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CRUD import settings
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Increase if you expect large imports

# =============================================================================
# FARMAI GIS Configuration
# =============================================================================
# Default map center coordinates (can be overridden per deployment)
# Set these to your target region's center point
FARMAI_DEFAULT_LAT = float(os.environ.get('FARMAI_DEFAULT_LAT', 31.4697))  # Default: Lahore, Pakistan
FARMAI_DEFAULT_LON = float(os.environ.get('FARMAI_DEFAULT_LON', 74.4101))
FARMAI_DEFAULT_ZOOM = int(os.environ.get('FARMAI_DEFAULT_ZOOM', 12))

# Maximum distance (km) from farm to field boundary centroid
FARMAI_MAX_FIELD_DISTANCE_KM = float(os.environ.get('FARMAI_MAX_FIELD_DISTANCE_KM', 50))

# Field area constraints (hectares)
FARMAI_MIN_FIELD_AREA_HA = float(os.environ.get('FARMAI_MIN_FIELD_AREA_HA', 0.00))
FARMAI_MAX_FIELD_AREA_HA = float(os.environ.get('FARMAI_MAX_FIELD_AREA_HA', 10000))