# Generated by Django 5.2.9 on 2026-01-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asset_id_alter_device_id_alter_farm_id_and_more'),
        ('imagery', '0002_alter_droneimage_id_alter_processedraster_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(help_text='Satellite image acquisition date')),
                ('minio_folder', models.CharField(help_text='MinIO folder path with band data', max_length=500)),
                ('ndvi_mean', models.FloatField(blank=True, help_text='Mean NDVI value', null=True)),
                ('ndvi_std', models.FloatField(blank=True, help_text='NDVI standard deviation', null=True)),
                ('ndvi_min', models.FloatField(blank=True, help_text='Minimum NDVI value', null=True)),
                ('ndvi_max', models.FloatField(blank=True, help_text='Maximum NDVI value', null=True)),
                ('ndwi_mean', models.FloatField(blank=True, help_text='Mean NDWI value', null=True)),
                ('ndwi_std', models.FloatField(blank=True, help_text='NDWI standard deviation', null=True)),
                ('ndwi_min', models.FloatField(blank=True, help_text='Minimum NDWI value', null=True)),
                ('ndwi_max', models.FloatField(blank=True, help_text='Maximum NDWI value', null=True)),
                ('band_data', models.JSONField(blank=True, help_text='JSON with statistics for all bands: {B01: {mean, std, min, max}, B02: {...}, ...}', null=True)),
                ('ndvi_image_path', models.CharField(blank=True, help_text='MinIO path to NDVI heatmap PNG', max_length=500, null=True)),
                ('ndwi_image_path', models.CharField(blank=True, help_text='MinIO path to NDWI heatmap PNG', max_length=500, null=True)),
                ('cloud_coverage', models.FloatField(blank=True, help_text='Cloud coverage percentage (0-100)', null=True)),
                ('valid_pixel_percentage', models.FloatField(blank=True, help_text='Percentage of valid (non-nodata) pixels', null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Any notes about processing or data quality')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_readings', to='core.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_readings', to='core.fieldboundary')),
            ],
            options={
                'verbose_name': 'Image Reading',
                'verbose_name_plural': 'Image Readings',
                'ordering': ['-acquisition_date'],
                'unique_together': {('field', 'acquisition_date')},
            },
        ),
    ]
